### ISSUE TITLE
Make processDependencyManagementTransitive as false by default

### ISSUE THREAD

**Issue by slawekjaranowski** [mojohaus/versions#1002]
In project when we use import in dependency management, 
by default many updates are reported which is not possible to change in project.

I think that more usable is to know that new version of imported pom is available.

**Comment by slawekjaranowski** [comment]
What do you think?

**Comment by slawekjaranowski** [comment]
@slachiewicz @ajarmoniuk ?

**Comment by ajarmoniuk** [comment]
+1

**Comment by slachiewicz** [comment]
+1

**Comment by slawekjaranowski** [comment]
Interesting exercise ... I raised an issues: #1004
