### ISSUE TITLE
display-parent-updates should support allowMajorUpdates, allowMinorUpdates and related parameters

### ISSUE THREAD

**Issue by cachescrubber** [mojohaus/versions#1016]
Since #966 (2.16.0) most `display-*-updates` and `update-*` goals consistently support a set of common parameters to narrow the scope of used dependencies (allowMajorUpdates, allowMinorUpdates, allowIncrementalUpdates, ...) However, **display-parent-updates** does not.

If you agree I'm happy to contribute a PR to make sure **display-parent-updates** accepts the same parameters as **update-parent**.

**Comment by slawekjaranowski** [comment]
PR are always welcome 😄 

Please pay attention that we have:
- versions:update-parent
- versions:display-parent-updates
- versions:parent-updates-report

Agree available options should be similar.

**Comment by cachescrubber** [comment]
Hi @slawekjaranowski , please have a look at #1017 

From the `*-report` goals, none is currently supporting the allMajor/Minor parameter.
