### ISSUE TITLE
"Includes"  in the set-properties goal does not seem to respect wildcards of the form com.foo.*

### ISSUE THREAD

**Issue by BenManifold** [mojohaus/versions#1027]
It isn't clear if this is supported from documentation, but CI scripting in one of my projects broke, in such a way that no includes of the form com.foo.* are respected, where we expect that to match to anything like "com.foo.bar". Instead, we have to list every possible groupID of that form, which creates a maintenance problem.

We're using 2.13.0

**Comment by slawekjaranowski** [comment]
can you try with the latest version - 2.16.2?

**Comment by BenManifold** [comment]
Was this a fixed issue? Sorry, I couldn't get a list of closed issues to come up.

**Comment by BenManifold** [comment]
My apologies, please disregard. This was shell variable shenanigans, and not a problem with the plugin.
