### ISSUE TITLE
Versions Maven Plugin 2.15.0 ignores allowMajorUpdates flag

### ISSUE THREAD

**Issue by tomaskodaj** [mojohaus/versions#1029]
There is problematic bug:

In spring boot 2.7.x, there is plugin version 2.10.0,
In spring boot 3.1.x, there is plugin version 2.15.0,
In spring boot 3.2.x, there is plugin version 2.16.2.

In version 2.15.0, there is bug, because it is ignoring configuration of allowMinor/allowMajor. It was okay in 2.10.0 and is fixed in 2.16.2.

Output of v. 2.15.0 - allow Major is false, but it updates major anyway:
```
[INFO] Assuming allowMajorUpdates false because allowMinorUpdates is false. 
[INFO] Updated ${somedependency.version} from 10.0.32 to 11.0.3 
```

Running the same script with 2.10.0 and 2.16.2 is correct and version is not updated...

Since spring boot policy is only to apply patches in older releases (3.1.x vs 3.2.x), is it possible to backport the fix from 2.16.2 also to 2.15.1?

Thanks

**Comment by slawekjaranowski** [comment]
We don't have a plan to maintain many branches for old versions - only the latest version is maintained.

Should be possible to put newer version in your project in `pluginManagement`
