### ISSUE TITLE
Incorrect implementation of org.codehaus.mojo.versions.CompareDependenciesMojo#getRemoteMavenProject method

### ISSUE THREAD

**Issue by rimvydasv** [mojohaus/versions#1067]
CompareDependenciesMojo.java
Lines 260 - 266

ProjectBuildingResult result = projectBuilder.build(
                remoteArtifact,
                true,
                PomHelper.createProjectBuilderRequest(
                        session,
                        r -> r.setProcessPlugins(false),
                        r -> r.setRemoteRepositories(session.getCurrentProject().getPluginArtifactRepositories())));

As far as I understand the last line should be:
 r -> r.setRemoteRepositories(session.getCurrentProject().getRemoteArtifactRepositories())));

**Comment by slawekjaranowski** [comment]
You can try to change implementation - and we see if ITs pass.

You can also add a specific IT which discover your problem.

We can also build set of `getPluginArtifactRepositories` and `getRemoteArtifactRepositories` and pass it as remote repositories

**Comment by andrzejj0** [comment]
I think it's an obvious mistake.
