### ISSUE TITLE
Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7

### ISSUE THREAD

**Issue by aayushi760** [mojohaus/versions#1105]
Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:display-plugin-updates (default) on project crs-catalog-core: Execution default of goal org.codehaus.mojo:versions-maven-plugin:2.7:display-plugin-updates failed. NullPointerException -> [Help 1]

Getting above error on running maven clean install
The plugin in pom.xml is 

<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.7</version>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>display-dependency-updates</goal>
                            <goal>display-plugin-updates</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by slawekjaranowski** [comment]
The latest version of plugin is `2.17.0` please try it.

Please also provide a stack output with executing `mvn -e ....`

As usual the minimal project which can reproduce issue will be appreciated.

**Comment by slawekjaranowski** [comment]
Please reopen when you have the same issue with the latest version of plugin
