### ISSUE TITLE
Enhancement: limit report to updates actionable in the context of pom.xml

### ISSUE THREAD

**Issue by rmie** [mojohaus/versions#1140]
I found nothing similar in closed issues, if you consider this a duplicate to a previous issue, feel free to close it.

**Motivation:**
I'm trying to limit the reports down to a point that all listed dependencies, plugins, parent and properties version are specified in the analyzed pom.xml. Basically all inherited (upstream) issues should be ignored. I want to make it as simple and fast as possible to fix such issues without the need to reason about if a reported issue is inherited from upstream.

**Example**: two projects, from different reactors

* parent/pom.xml uses spring-boot-starter-parent:3.3.1, but 3.3.3 is latest version
* service/pom.xml uses parent/pom.xml at latest version

report for
* parent/pom.xml 
  * MUST list outdated parent
  * MUST NOT list e.g. outdated plugins, dependencies that are inherited from spring-boot-starter-parent
* service/pom.xml
  * MUST NOT list e.g. outdated parent, plugins etc. inherited from parent/pom.xml

**Possible Solutions**:

* preferred, additional flag e.g. _ignoreInherited_ to control this behavior
* alternative, mark "inherited" issues in reports (and possibly xml) as such

**Comment by andrzejj0** [comment]
Have you tried *processDependencyManagementTransitive*?

**Comment by rmie** [comment]
> Have you tried setting _processDependencyManagementTransitive_ to false?

yes

**Comment by andrzejj0** [comment]
I can't reproduce the issue when using -DprocessDependencyManagementTransitive=false. 

Please provide a minimal pom.xml (or set of maven projects) reproducing the issue.

**Comment by rmie** [comment]
The testcase is made up of two poms, parent/pom.xml and child/pom.xml, intentionally not placed in a single reactor build.

running _mvn -f child/pom.xml' versions:display-dependency-updates_ gives 

```
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   com.oracle.database.jdbc:ojdbc11 ............ 21.9.0.0 -> 23.6.0.24.10
...
[INFO] The following dependencies in pluginManagement of plugins have newer versions:
[INFO]   org.springframework.boot:spring-boot-maven-plugin ..... 3.3.4 -> 3.3.5
```

The version of neither of both is directly specified in _child/pom.xml_, but inherited from _parent/pom.xml_, and both are ignored by e. g. _versions:use-latest-version_. This makes it hard to reason about what e. g. _versions:use-latest-version_ will change.

**Comment by andrzejj0** [comment]
I'm missing the actual pom.xml files to be able to reproduce your case.

**Comment by andrzejj0** [comment]
Thanks for the update. Not exactly sure how to tackle this. The plugin has a history and its goals do differ in behaviour ever so slightly. For example, `use-latest-versions` doesn't process any dependencies within build plugins or `pluginManagement`, `display-dependency-updates` does do it (which can be disabled e.g. by *processPluginDependencies* or *processPluginDependenciesInPluginManagement*), hence it displays the updates there (`spring-boot-maven-plugin`) whereas `use-latest-versions` doesn't.

Regarding the version of `ojdbc11` -- it's assigned by Maven based on parent of the parent. This should probably not be reported by `display-dependency-updates` especially considering the fact that you did disable transitive dependencies.

**Comment by andrzejj0** [comment]
Same thing is true about e.g. `dependency-updates-report`, which also outputs dependencies managed by parent in this case, because the that Mojo, too, operates on the Maven interpolated model. 

No, those two goals (report and display) only share some version retrieval generic code.

**Comment by rmie** [comment]
IMHO it would be already helpful to add information about the origin of the issue, similar to what _help:effective-pom -Dverbose_ does:

```xml
      <dependency>
        <groupId>com.oracle.database.jdbc</groupId>  <!-- org.springframework.boot:spring-boot-dependencies:3.3.4, line 1347 -->
        <artifactId>ojdbc11</artifactId>  <!-- org.springframework.boot:spring-boot-dependencies:3.3.4, line 1348 -->
        <version>21.9.0.0</version>  <!-- org.springframework.boot:spring-boot-dependencies:3.3.4, line 1349 -->
      </dependency>
```

From this, one would immediately know where to go to fix it.

**Comment by andrzejj0** [comment]
Very good idea.

**Comment by andrzejj0** [comment]
Okay. I'll make the option controlling this false by default (that is, the plugin will keep its old behaviour by default).

It's a good idea about showing the location of the dependency in those cases, much like what `dependency:tree` does, so I'll add that as well.

I'm currently trying to use a common component for displaying dependencies, dependency reports, and perhaps even updates, but that's probably for a longer shot.
