### ISSUE TITLE
Enhance documentation for ignoring (alpha|beta)

### ISSUE THREAD

**Issue by onacit** [mojohaus/versions#1144]
I just found that the following example documented on [Version number rules](https://www.mojohaus.org/versions/versions-maven-plugin/version-rules.html#Using_the_ruleSet_element_in_the_POM) may be enhanced.

```
  <version>.+-(alpha|beta)</version>
```

Since any `alpha` or `beta` releases may has additional sequence number after the word, it would be nice the example show like,

```
  <version>.+-(alpha|beta).+</version>
```

Thanks.

**Comment by slawekjaranowski** [comment]
PR is welcome ... simply edit: https://github.com/mojohaus/versions/blob/master/versions-maven-plugin/src/site/markdown/version-rules.md.vm

output can be checked by executing `mvn site site:stage` and look into `target/staging`

**Comment by onacit** [comment]
@slawekjaranowski As you wish, Milord.
https://github.com/mojohaus/versions/pull/1145
