### ISSUE TITLE
Remove non-functional dynamic version goal

### ISSUE THREAD

**Issue by jimisola** [mojohaus/versions#1158]
After more clarification it is clear that the dynamic version goal will not work fully with Maven due to way that properties are handle.

The functionality of dynamic versioning have been implemented (ported) to @cstamas Maveniverse Nisse instead. See: https://github.com/maveniverse/nisse/issues/9

This is also better in line with the  coming Maven 4.

**Comment by slawekjaranowski** [comment]
PR are welcome ... 

I hope that as new - is not widely used.
