### ISSUE TITLE
Cleanup Plexus Utils, convergence with Maven 4 step 1

### ISSUE THREAD

**Issue by andrzejj0** [mojohaus/versions#1169]
Clean up deprecated methods.
Try to get rid as much as possible of Plexus Utils, see e.g. MNG-6825, MNG-7820.

This exercise focuses primarily on easy targets such as eliminating Plexus StringUtils in favour of Apache Commons etc.

The ultimate goal is to ease the upgrade to the upcoming changes from Maven 4.

**Comment by slawekjaranowski** [comment]
I think that we not need an issue where we immediately provide PR.
Simply we can describe what we do in PR.

For me issue is useful when we want discus something before implementing or put on task list to do.

What do you think?

We can clarify it in README ...

**Comment by andrzejj0** [comment]
Noted!

**Comment by andrzejj0** [comment]
I think it does serve one important purpose though -- it lets us track progress on development. For example, I'm currently busy replacing ModifiedPOMXMLEventReader with a similar class based on Stax2, not using plexus xml anymore.
