### ISSUE TITLE
Log4j 2.12.1 getting download it when running pluggin commands

### ISSUE THREAD

**Issue by rogelio-blanco** [mojohaus/versions#1175]
Hi team, 

I want to raise the issue that when I run a command using this plugin in the .m2 folder, I get a log4j 2.12.1 version with multiple vulnerabilities. Our Security team is asking to upgrade to a higher version.

I already verify:
- Our pom. doesn't have any reference to this log4j version.
- I also cloned the plugin project to check if I could exclude the dependency, but I could not see it.
- When I run a clean install in my project, I don't see that dependency being downloaded; I see it when I run the command to upgrade the POM version.

How can I get around to downloading that log4j version? I would appreciate any help or feedback you can give me.

**Plugin version:** 2.17.1
**Command:** version:set versions:commit -DnewVersion="dummy"

![image](https://github.com/user-attachments/assets/43918746-f4a5-4ebb-8c36-6e8c13e884c4)

https://security.snyk.io/package/maven/org.apache.logging.log4j:log4j-core/2.12.1

**Comment by andrzejj0** [comment]
We don't use log4j. It's most likely a transitive dependency of your project. You can use `dependency:tree` to track what dependency is using it.

```sh
mvn dependency:tree -Dverbose | grep -C 8 log4j
```

**Comment by slawekjaranowski** [comment]
You can also try with: `maven.repo.local.recordReverseTree` property, exxecute your example as:
```
mvn -Dmaven.repo.local.recordReverseTree version:set ....
```

next examine content of directories: `.tracking` in your `~./m2/repository`

**Comment by rogelio-blanco** [comment]
Thank you for the quick response; the commands help me.   Below, you can see the output, which indicates that the plugin the one that is importing that specific dependency.

![image](https://github.com/user-attachments/assets/b7c707cc-8b4d-4301-a7c4-eefee065a8b7)

**Comment by andrzejj0** [comment]
Apologies for closing this. `dependency:tree` did not include any descendants of `commons-logging` for some reason. `log4j` looks to be an optional dependency of it.

This should be resolved by #1168

**Comment by slawekjaranowski** [comment]
It is strange ... optional dependencies should not be downloaded .... we need more investigation in Maven/Resolver 

By the wat should be resolved with new version of doxia.

**Comment by andrzejj0** [comment]
@slawekjaranowski in case you're interested, here's the output of 

```shell
rm -rf ~/.m2/repository/log4j/log4j; mvn -X versions:set versions:revert -DnewVersion=dummy | tee /tmp/versions.log
```

[versions.log](https://github.com/user-attachments/files/17688761/versions.log)
