### ISSUE TITLE
Set version stopped working in 2.18.0

### ISSUE THREAD

**Issue by mariuszpala** [mojohaus/versions#1189]
After the recent 2.18.0 release the plugin stopped working.
When I run this cmd

` mvn versions:set -DnewVersion=5.13.0.3`

I get an exception:

```
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.18.0:set (default-cli) on project cara-data-model: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.18.0:set failed: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.18.0:set (default-cli) on project cara-data-model: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.18.0:set failed: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null


Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
    at java.util.regex.Matcher.getTextLength (Matcher.java:1808)
    at java.util.regex.Matcher.reset (Matcher.java:461)
    at java.util.regex.Matcher.<init> (Matcher.java:256)
    at java.util.regex.Pattern.matcher (Pattern.java:1180)
    at org.codehaus.mojo.versions.SetMojo.execute (SetMojo.java:375)

```

**Comment by mariuszpala** [comment]
Actually it looks like I get the same error in older versions as well, it used to be working fine few weeks back and it suddently stopped working, any idea what might be the cause? Maven version is 3.9.9

**Comment by mariuszpala** [comment]
It works with 2.8.1 but not with 2.9.0 onwards

**Comment by slawekjaranowski** [comment]
can you provide a simple project which reproduce your issue?

**Comment by mariuszpala** [comment]
That's the problem. This is working for for other team members with same Java and Maven version, it used to work fine for me as well, but it suddenly stopped and I don't know why. With 2.8.1 version everything works fine, with newer it is not. Are you able to guess from the source code what that issue might be related with?

**Comment by andrzejj0** [comment]
```java
if ((groupIdRegex == null || groupIdRegex.matcher(mGroupId).matches())
```

`mGroupId` (which is the `groupId` of the project) is `null`. Let's see...

**Comment by andrzejj0** [comment]
@mariuszpala you need to try to come to a minimal set of Maven pom.xml files reproducing this.

**Comment by mariuszpala** [comment]
This is really weird, yesterday it was failing in general on all projects with version > 2.8.1, with groupId defined, today it works like a charm again with latest version... Very strange
