### ISSUE TITLE
`display-dependency-updates` with `processDependencyManagementTransitive = false` ignores `dependencyManagement` in enabled profiles

### ISSUE THREAD

**Issue by facboy** [mojohaus/versions#1191]
When running `display-dependency-updates` with `processDependencyManagementTransitive` is disabled (i.e. `false`), `dependencyManagement` in enabled profiles is not checked for updates.

**Comment by andrzejj0** [comment]
From what I see, this has never worked correctly since the introduction of processDependencyManagementTransitive. 

Reproduced.
