### ISSUE TITLE
compare-dependencies goal improvements

### ISSUE THREAD

**Issue by jlosornogil** [mojohaus/versions#123]
I have a need in my CI process and your versions-maven-plugin has been very useful, thanks for it. But right now we need to incorporate a pair of modifications in the functionality of the plugin (specifically in the compare-dependencies goal). 

1. Add an optional parameter to exclude one scope from the comparison. We have an use case where we want to compare only non-test dependencies.

2. Add an optional parameter “scriptableOutput” to generate the comparison report in a machine-readable manner. 

We would like to get your opinion about these changes. Do you think the changes could be included in the release if we PR?

Thanks in advance!

**Comment by khmarbaise** [comment]
First these are two improvements. Furthermore of course patches or (pull requests) are always welcome...
