### ISSUE TITLE
RFE: Handle artifacts that move to new GAV?

### ISSUE THREAD

**Issue by ThrawnCA** [mojohaus/versions#374]
Sometimes artifacts move to a different GAV signature, so they're out of date but no further updates appear. Is it feasible to detect this as a new version and include it in the report?

Failing that - or in addition - perhaps there could be a report on dependencies that appear to be the latest version, but are years old? That could be a clue that either they've moved to a new GAV, or they're no longer maintained.

**Comment by obfischer** [comment]
Sounds like a reasonable addition for me, but I don't know if the required date information are available to Maven.

**Comment by ThrawnCA** [comment]
I still think this has value.

**Comment by slawekjaranowski** [comment]
It can be possible only if artifacts maintainers prepare proper relocation information.

https://maven.apache.org/guides/mini/guide-relocation.html
