### ISSUE TITLE
possible new feature

### ISSUE THREAD

**Issue by clembo590** [mojohaus/versions#596]
Hello. I am here to post about a "possible" new goal.
When you are working on a multi module there is this goal:
`update-child-modules` that allows to make sure that all children are actually up to date with the current parent.
In order to do that we need to execute: `mvn -N versions:update-child-modules`. (By the way it would be nice if the `-N` could be on the documentation page of the goal itself not on some `how to  page`).

What I am suggesting is to go a step further and create  a new goal that would do the same  PLUS that for all the Artifacts that are produced by the multimodule, would update the dependency version and dependencyManagement version in all the pom files of the multiModule project.

simple example:
I have a multimodule: (it does not matter if it is  parenting of aggregation)

Parent:
-child1(v0)
-child2(v0)

child2 has a dependency to child1. I make a change in child1 and update its pom file with the new version and so I get child1(v1).
The new goal will update the pom file of child2 so that now child2 depends on child1(v1).

Notice that I do not want to use latest version here: what I want is to make sure that what is produced by the multimodule  is actually used.

I would call that goal `link-all-modules`.

This is very usefull if you have a big multiModule project.

**Comment by sellersj** [comment]
Do all the child modules share the parent version?

If so, in child2 for it's dependency to child1 can you not just set the version to be ${project.version} ?

**Comment by clembo590** [comment]
@sellersj sorry for the delay in the answer
no: the point would be to have all versions completly independent.
