### ISSUE TITLE
use-latest-versions  or use-latest-releases stays on latest snapshot when newer release doesn't exists

### ISSUE THREAD

**Issue by PatrickSauts** [mojohaus/versions#600]
`
mvn versions:use-latest-versions -Dincludes=pos-integration:* -DgenerateBackupPoms=false -DallowMajorUpdates=true -DallowMinorUpdates=true -DallowSnapshots=true
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< pos-integration:rest-api-server >-------------------
[INFO] Building rest-api-server 0.4.5-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.11.0:use-latest-versions (default-cli) @ rest-api-server ---
[INFO] Major version changes allowed
[INFO] Updated pos-integration:rest-api-core:jar:0.3.7 to version 0.3.8-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.801 s
[INFO] Finished at: 2022-06-16T00:56:51+02:00
[INFO] ------------------------------------------------------------------------

`

then

`
mvn versions:use-latest-versions -Dincludes=pos-integration:* -DgenerateBackupPoms=false -DallowMajorUpdates=true -DallowMinorUpdates=true -DallowSnapshots=false
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< pos-integration:rest-api-server >-------------------
[INFO] Building rest-api-server 0.4.5-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.11.0:use-latest-versions (default-cli) @ rest-api-server ---
[INFO] Major version changes allowed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.585 s
[INFO] Finished at: 2022-06-16T00:56:58+02:00
[INFO] ------------------------------------------------------------------------

`

version of the dependency should have been put back to the latest release.
There is no 3.8.0 release version

**Comment by ajarmoniuk** [comment]
@PatrickSauts for `use-latest-versions`, you need to use `allowDowngrade`. It will not downgrade any versions otherwise.
