### ISSUE TITLE
Will versions:update-parent allow more customize settings

### ISSUE THREAD

**Issue by SingKS8** [mojohaus/versions#628]
Some projects like spring boot has different version series, today, they have 2 release 2.7.2 and 2.6.10, if I use "`versions:update-parent -DallowSnapshots`", the plugin will ignore `parentVersion` and only find the number latest version 3.0.0-SNAPSHOTS, this is other version series. In my case, I just care about 2.7.x version series update, so now writing some script for testing pipelines is painful.

**Comment by slawekjaranowski** [comment]
Did you try a `allowMajorUpdates` and `allowMinorUpdates`?

https://www.mojohaus.org/versions/versions-maven-plugin/update-parent-mojo.html

**Comment by SingKS8** [comment]
I have reviewed my code the versions-maven-plugin version is 2.12.0 when I submitted this issue, I will try those parameters, and I think this issue should be closed
