### ISSUE TITLE
New Feature : Exclude intermediate Minors

### ISSUE THREAD

**Issue by sultan** [mojohaus/versions#730]
The suggested filter would filter out to exclude verbose intermediate versions, to keep only, in this example :

* 10.0.26
* 10.1.0

the filter/algo would act beginning at the very last, taking minor prefix "10.1." and filter out every other version string starting with "10.1." then finding another Minor, extracting "10.0." and filter out again, etc, until end of list.

![image](https://user-images.githubusercontent.com/5782559/193446173-60c8387b-7b31-4e69-a790-fea03ba22102.png)

**Comment by sultan** [comment]
Result with new code

![image](https://user-images.githubusercontent.com/5782559/193449297-e818fb06-1e64-4e2c-9437-fdbd722a3db0.png)

**Comment by sultan** [comment]
the filter has been rethinked as so:
at most two versions per Major.Minor: latest release + following latest pre-release versions

**Comment by sultan** [comment]
this could be de/activated with a flag
-Dversions.reportLength=FULL
-Dversions.reportLength=SHORT

@ajarmoniuk is there any rull for the flags names?

**Comment by ajarmoniuk** [comment]
Not that I know of :)

**Comment by ajarmoniuk** [comment]
@sultan are you still going to work on this?

**Comment by sultan** [comment]
Still on my todo list. I am having difficulties knowing where to put my filter. I can't get it to be streamable. And not sure where to put it after the api used streams. Any advice appreciated.
