### ISSUE TITLE
Support for reporting new extenions versions

### ISSUE THREAD

**Issue by obfischer** [mojohaus/versions#74]
The Maven Versions Plugin already supports the reporting of new plugin versions (`versions:plugin-updates-report`) and new versions of dependencies (`versions:dependency-updates-report`). 

If not already supported, please enhence the Maven Versions Plugin also to report new versions of Maven extensions.

**Comment by obfischer** [comment]
I would like to provide a patch for this feature request.

**Comment by famod** [comment]
@obfischer have you ever gotten round to implementing this?

**Comment by delanym** [comment]
@famod doesn't look like it https://github.com/obfischer/fork-of-versions-maven-plugin

50 open pull requests :(

**Comment by ajarmoniuk** [comment]
Okay

**Comment by ajarmoniuk** [comment]
Will do this in stages. First - `display-extension-updates`.

**Comment by theit** [comment]
@ajarmoniuk Are there any news on this issue? I've seen your commits, and they look very promising (at least to me) :-)

**Comment by ajarmoniuk** [comment]
No news, the PR is waiting to be merged.

**Comment by theit** [comment]
Is there help needed with something?

**Comment by ajarmoniuk** [comment]
I don't think so. From what I can gather, Sławek (the main maintainer) is currently quite busy with Maven 4-related issues.

**Comment by theit** [comment]
Ok, thanks. Have you seen my [comment](https://github.com/ajarmoniuk/versions-maven-plugin/commit/1e4bd55238e686ee6757de39ffd2ba21c1febe23#r109271112) on your latest commit?

**Comment by ajarmoniuk** [comment]
Can't see any comment. Let me check...
