### ISSUE TITLE
Enhancement: display update information for ranges

### ISSUE THREAD

**Issue by sultan** [mojohaus/versions#767]
when one uses ranges everywhere the reports are blank which does not help.

![image](https://user-images.githubusercontent.com/5782559/196413415-b7593f3a-1102-429d-86b1-ae1d67d36281.png)

with range [2.0,3) the user could benefit from:
* summary suggest update to, let's say, [2.1,3)
* details also display omitted version to let them know major versions exist

a blank report wrongly let the user believe no major version exists when there are

we should let them know there new versions, but outside the range they chose.

**Comment by sultan** [comment]
note:
the property report has the major versions (outside range) shown, but lacks minor ones (inside range not shown)
the dependencies report has non shown

**Comment by ajarmoniuk** [comment]
Hi, are you still working on this?

**Comment by ajarmoniuk** [comment]
I'll check 👍

**Comment by sultan** [comment]
note to self: one solution to my problem requires rework the cache to add the method as parameter (lambda)
