### ISSUE TITLE
new feature request update-snapshots

### ISSUE THREAD

**Issue by shivushedad** [mojohaus/versions#800]
My multi module project structure:
Parent
  - Child module 1
  - Child module 2
  - Child module 3
  - ...
  - Child module 12

When I am doing development there are cases where I would be modifying code on more than 2 child modules.

`mvn versions:use-releases` has helped me in my local development to make sure I update to releases from snapshot thereby automating some of my development tasks. However the other way around has not been possible with the options we have today with versions plugin.

Essentially I want to do this:
`mvn versions:use-snapshots -Dincludes=groupId1:artifactId1,groupId2:artifactId2`
and maven would update those dependencies to use `12.23.45-SNAPSHOT` from `12.23.45`

I could not find this ability in either maven core functionality or in any other community plugin. Since versions plugin mostly deals with the dependency versions - I feel this plugin would be best place for this ability to exist.

**Comment by slawekjaranowski** [comment]
Did you try: `use-next-snapshots` https://www.mojohaus.org/versions-maven-plugin/use-next-snapshots-mojo.html?
