### ISSUE TITLE
Bug: Versions Ranges not accounted for

### ISSUE THREAD

**Issue by sultan** [mojohaus/versions#824]
there are bugs in the getAll updates and consort where ranges filters nothing.

this is because the restrictionFor method yields a "Restriction" in all cases even when the version is a range spec string. ex for string "[1.0,2.0),[3.0,4.0)" then restrictionFor yields a Restriction instead of a VersionRange. then the restriction instanciated has a no upper bound and a lower bound of "[1.0,2.0),[3.0,4.0)". when asked, this restriction does not filter

one range spec can have multiple restrictions, and multiple 'lower bound'.
we want the highest one, or don't we?

for an empy/all scope [1.0,2.0),[3.0,4.0) -> display updates in range (3.0,)

for other scopes this might have no meaning and will yield unexpected result.

**Comment by sultan** [comment]
Here one could expect to have the versions lower than range filter out. and higher versions displayed with star

![image](https://user-images.githubusercontent.com/5782559/203547622-f7cb6528-49c7-4194-abdb-a840a70e7858.png)

**Comment by sultan** [comment]
the person that wrote 3.0.12 on its range spec would want:

these versions filtered out:
* 3.0.11 because its too low
* 3.0.12 because not an update of 3.0.12 itself 

these versions displayed with star:
* 4.0.0-Mx, because outside range

**Comment by sultan** [comment]
a correct algorithm might be over complicated, i suggest one simple algo:

within one range spec, of all its restrictions, take all the lower bounds.
of all of them take the highest. we call it the highestLowerBound.

we create a restriction with restrictionFor with this bound as lower bound and compute the upper bound with the segment asked

**Comment by sultan** [comment]
note that current algos filters snapshot twice

**Comment by sultan** [comment]
```java
            try
            {
                // one range spec can have multiple restrictions, and multiple 'lower bound', we want the highest one.
                // [1.0,2.0),[3.0,4.0) -> 3.0
                ArtifactVersion highestLowerBound = null;
                VersionRange range = VersionRange.createFromVersionSpec( getCurrentVersion().toString() );
                for ( Restriction restriction : range.getRestrictions() )
                {
                    ArtifactVersion lowerBound = restriction.getLowerBound();
                    if ( highestLowerBound == null || lowerBound != null
                            && getVersionComparator().compare( highestLowerBound, lowerBound ) < 0 )
                    {
                        highestLowerBound = lowerBound ;
                    }
                }
                if ( highestLowerBound == null )
                {
                    highestLowerBound = getCurrentVersion();
                }
System.out.println( "highestLowerBound: " + highestLowerBound );
                Restriction restriction = getVersionComparator().restrictionFor( highestLowerBound, updateScope );

                boolean includeSnapshots1 = isIncludeSnapshots();
                return Arrays.stream( getVersions( includeSnapshots1 ) )
                        .filter( candidate -> includeSnapshots1 || !ArtifactUtils.isSnapshot( candidate.toString() ) )
                        .filter( candidate -> isVersionInRestriction( restriction, candidate ) )
                        .sorted( getVersionComparator() )
                        .distinct()
                        .toArray( ArtifactVersion[]::new );
            }
            catch ( InvalidVersionSpecificationException | InvalidSegmentException ignored )
            {
                // ignored

```

**Comment by ajarmoniuk** [comment]
If you come up with a PR, please create integration tests for issues found. 👍

**Comment by sultan** [comment]
> If you come up with a PR, please create integration or unit tests for issues found. 👍

sure ! i would not want the issue to come back :)

**Comment by sultan** [comment]
edge case

![image](https://user-images.githubusercontent.com/5782559/203964404-f946d799-649f-443a-9259-daf3cb8f2046.png)

**Comment by ajarmoniuk** [comment]
> @ajarmoniuk i tried to fix using BoundArtifact, no success yet. Is BoundArtifact's segment parameter there to discriminate between upper bound 4.0] vs 4.0.0] ?
> 
>     * does 4.0] allows both 4.0 and 4.0.1 ?
>     * does 4.0.0] allows 4.0.0 but not 4.0.1 ?


1. There is no difference between 4.0.0 and 4.0 or 4.

They are the same version in the Maven versioning system.

Please compare https://maven.apache.org/pom.html#version-order-specification

> Then, starting from the end of the version, the trailing "null" values (0, "", "final", "ga") are trimmed. This process is repeated at each remaining hyphen from end to start.
> 
> Trimming Examples:
> 
>     1.0.0 -> 1
>       1.ga -> 1
>       1.final -> 1
>       1.0 -> 1
>       1. -> 1
>       1- -> 1
>       1.0.0-foo.0.0 -> 1-foo
>       1.0.0-0.0.0 -> 1

2. `BoundArtifactVersion` has a `segment` argument in its constructor, which specifies the segment on which the infinite upper boundary is set. Then it acts as if it had +∞ as its upper bound on all segments less major than the held segment.

So, BoundArtifactVersion with version "4" (without any zeros) and the segment set to INCREMENTAL should allow 4.0.*. If it doesn't then it's a bug, I'll gladly have a look.

3. `BoundArtifactVersion` does not have a notion of `)` or `]`, it's not a restriction, it is a "version" with a wildcard on the given position. If you want to create a restriction, you should use a different object. 

So, again, 

> >     * does 4.0] allows both 4.0 and 4.0.1 ?
>     * does 4.0.0] allows 4.0.0 but not 4.0.1 ?

No notion of "]" in BoundArtifactVersion.

**Comment by ajarmoniuk** [comment]
> if i want 4) excl. instead, should i split BoundArtifact into 2 impl ? (ExclusiveBoundArtifact (new) and InclusiveBoundArtifact (current impl)

it's not the purpose of this to have a restriction, please use the Restriction object

**Comment by sultan** [comment]
ok, thanks for the update ! its clear in my head now.
i think my case needs another impl anymway because of 

> edge case.
> also, BoundArtifact does not account for Maven's infinite segments count. one might use range like ( 1.2.3.4.5 , 5.6.7.8.9 ) which cause invalid Segments. that would mean i might need another implementation

**Comment by ajarmoniuk** [comment]
Or better yet: just state in the documentation of the report that we don't support such cases :)

**Comment by sultan** [comment]
that breaks in the cases of my own needs haha 😅 so given time i may find a solution, but yeah not supporting this case might help promote semver

**Comment by sultan** [comment]
note to self, there is 2 kinds of upper bounds:
* one kind constructed from lower bound
 * 1.0 + SUB => [ 1 , 1.0.0.∞ ]
 * 1.0 + INC => ( 1.0.0.∞ , 1.0.∞ ]
 * 1.0 + MIN => ( 10.∞ , 1.∞ ]
 * 1.0 + MAJ => ( 1.∞ , ∞ ]
* one kind constructed from upper bound
 * [ 1.0 , 3.0 ) => [ 1 , 2.∞ ]

**Comment by ajarmoniuk** [comment]
Please be aware that you can also restrict from the other side -- to get an inclusive limit on 1.0.∞] you can use (1.1.0.

And vice-versa.

**Comment by sultan** [comment]
there must be multiple ways of expressing the same thing but i have to account that alphas, snapshots and sp1 still gets in the correct ranges without hard coding them

**Comment by sultan** [comment]
thoughts: the star system should tell the truth on how maven will translate the spec range in terms of accepted versions or not
* we may tweak with the versions ranges on the summary to move milestones on the right columns
* the details tables should make displays about star congruent with the Maven version being executed.

**Comment by sultan** [comment]
this display is correct, the user has to change the range with 

![image](https://user-images.githubusercontent.com/5782559/204006502-04eeea89-126b-4f89-883b-f34e4464db15.png)

**Comment by sultan** [comment]
same with [3.0.11, 4-a) or change Maven itself

![image](https://user-images.githubusercontent.com/5782559/204007231-70d8277e-5436-4177-b3fb-816cef7229f4.png)
