### ISSUE TITLE
display-property-updates includes parent projects since version 2.13.0

### ISSUE THREAD

**Issue by amottier** [mojohaus/versions#843]
Since version `2.13.0`, `display-property-updates` includes updates available for parent projects.

This can be an issue for example if parent is `spring-boot-starter-parent` version `2.7.6`. This is because `spring-boot-dependencies` (parent of `spring-boot-starter-parent`) specifies all its dependencies using properties and for most of them a more recent version exist.

I look at the [documentation](https://www.mojohaus.org/versions-maven-plugin/display-property-updates-mojo.html) but I can't find a parameter to get back to the previous behavior.

This issue can be reproduce with this [project](https://gitlab.ow2.org/amottier/demo-issue-display-property-updates) by comparing output of `./mvnw org.codehaus.mojo:versions-maven-plugin:2.12.0:display-property-updates` and `./mvnw org.codehaus.mojo:versions-maven-plugin:2.13.0:display-property-updates`.

**Comment by slawekjaranowski** [comment]
Resolved by #817

Please retest with latest snapshot version - 2.14.0-SNAPSHOT

**Comment by amottier** [comment]
@slawekjaranowski Thanks a lot for pointing me in the right direction, I can confirm that 2.14.0-SNAPSHOT fix the issue (and thanks @ajarmoniuk for #817 :+1:).
