### ISSUE TITLE
Parameter newVersion is not working with version 2.14.0

### ISSUE THREAD

**Issue by petro1** [mojohaus/versions#853]
mvn --settings **** -f common/pom.xml build-helper:parse-version versions:set -DnewVersion=2.0.0
[INFO] Processing change of common:1.0.0 -> 2.0.0
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for common 1.0.0

replace with the new version is not working

**Comment by slawekjaranowski** [comment]
please retest with `2.14.1`
