### ISSUE TITLE
Versions Maven Plugin updates random Module subsets with 2.14.1

### ISSUE THREAD

**Issue by jwachter** [mojohaus/versions#858]
Environment
-------------

- Maven Multimodule Project with 295 Modules in a strict parent-child hierarchy
- Maven Wrapper using Maven 3.8.6
- Calling `mvnw.cmd` or `./mvnw` with `versions:set -DnewVersion=1.2.3-SNAPSHOT -DgenerateBackupPoms=false`

Observed Behavior
-------------------

On multiple runs it is not deterministic which versions are updated:

- Run 1: 135 of 295 are not updated after BUILD SUCCESS (All children of a sub-parent)
- Run 2: 0 of 295 are not updated after BUILD SUCCESS
- Run 3: 3 of 295 are not updated after BUILD SUCCESS
- Run 4: 138 of 295 are not updated after BUILD SUCCESS (Children in multiple disjoint sub-parent hierarchies)

One of the sub parent hierarchies that seems to be always involved (partially) when something is not updated contains a single level of ~140 children but still not always only that hierarchy or a specific number of the children is affected.

With 2.14.0 it seems to not be broken yet for the same amount of test runs.

As this seems somewhat like a typical race condition we suspect that the introduction of  `parallelStream` in this line combined with a non-concurrent Map might be problematic: https://github.com/mojohaus/versions/commit/c74ced27d704d6a3d1bad9c916da3203e170f2de#diff-f58ee99d4e29219ee1519ba59712674919933915a6485ab987093718d0b773dbR1359

Expected Behavior
-------------------

All modules are consistently updated.

**Comment by ajarmoniuk** [comment]
Thanks for the bug report. I think it's rather `(files::add)` which causes the problem in combination with `parallelStream`.

**Comment by ajarmoniuk** [comment]
@corebonts there's also https://github.com/mojohaus/versions/blob/master/versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java#L375 

here, the non-thread safe collection is modified from within a parallel stream

please add that to your branch if you want
