### ISSUE TITLE
The plugin should print an excplicit error message if the maven version is lower than the 3.2.5

### ISSUE THREAD

**Issue by ajarmoniuk** [mojohaus/versions#866]
There's too many confused users reporting guice errors raised because the new components cannot be resolved. I think returning an error message could clear the confusion a bit.

**Comment by pzygielo** [comment]
I'm shocked this plugin is not using https://maven.apache.org/pom.html#Prerequisites!

**Comment by pzygielo** [comment]
2.13.0 - has it.

**Comment by ajarmoniuk** [comment]
> 2.13.0 - has it.

If it does, how come there are so many users running an older version of maven and reporting errors only now once they upgraded to 2.14.0?

**Comment by pzygielo** [comment]
80bf105dd30a7131da56f13ebd41c44824abb479 - plugin w/o prereq
c9c1396f8cbbe8f369d73ceae2f18b30a51f66bd - prereq removed from top-parent

```
2.11.0/versions-maven-plugin-2.11.0.pom:    <mavenVersion>3.0.5</mavenVersion>
2.12.0/versions-maven-plugin-2.12.0.pom:    <mavenVersion>3.2.5</mavenVersion>
```

**Comment by ajarmoniuk** [comment]
Anyway, thanks. I was going for a check using `RuntimeInformation` 🤡

**Comment by pzygielo** [comment]
> If it does, how come there are so many users running an older version of maven and reporting errors only now once they upgraded to 2.14.0?

I don't know. They lie?

apache-maven-3.0.5:
```
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.12.0:help (default-cli) on project standalone-pom: The plugin org.codehaus.mojo:versions-maven-plugin:2.12.0 requires Maven version 3.2.5 -> [Help 1]
```

```
[INFO] --- versions-maven-plugin:2.14.0:help (default-cli) @ standalone-pom ---
[INFO] Versions Maven Plugin 2.14.0
  The Versions Maven Plugin is used when you want to manage the versions of
  artifacts in a project's POM.

This plugin has 35 goals:

versions:commit
```

This shows - that prerequisite IS BEING checked by maven, even so old as 3.0.5, as long as plugin declares it.
2.14.0 doesn't - and `:help` is executing fine (as doesn't need much more from maven 3.2.5).

**Comment by ajarmoniuk** [comment]
Checked with 3.2.1 to the same results. I guess they probably moved from a version which did not feature that thing in pom.xml.

**Comment by ajarmoniuk** [comment]
Anyhoo, it does the job.

**Comment by slawekjaranowski** [comment]
It was disappeared somehow during split project to modules  😄 

Some time ago I have an idea ... https://issues.apache.org/jira/browse/MPLUGIN-418 
I see that should be implemented

**Comment by slawekjaranowski** [comment]
> [80bf105](https://github.com/mojohaus/versions/commit/80bf105dd30a7131da56f13ebd41c44824abb479) - plugin w/o prereq [c9c1396](https://github.com/mojohaus/versions/commit/c9c1396f8cbbe8f369d73ceae2f18b30a51f66bd) - prereq removed from top-parent
> 
> ```
> 2.11.0/versions-maven-plugin-2.11.0.pom:    <mavenVersion>3.0.5</mavenVersion>
> 2.12.0/versions-maven-plugin-2.12.0.pom:    <mavenVersion>3.2.5</mavenVersion>
> ```

so I removed prerequisites from parent and forgot add to plugin module  ... You do not have to thank me 😕

**Comment by ajarmoniuk** [comment]
Happens to the best 😉

**Comment by pzygielo** [comment]
> > [80bf105](https://github.com/mojohaus/versions/commit/80bf105dd30a7131da56f13ebd41c44824abb479) - plugin w/o prereq [c9c1396](https://github.com/mojohaus/versions/commit/c9c1396f8cbbe8f369d73ceae2f18b30a51f66bd) - prereq removed from top-parent
> > ```
> > 2.11.0/versions-maven-plugin-2.11.0.pom:    <mavenVersion>3.0.5</mavenVersion>
> > 2.12.0/versions-maven-plugin-2.12.0.pom:    <mavenVersion>3.2.5</mavenVersion>
> > ```
> 
> so I removed prerequisites from parent and forgot add to plugin module

This was not helping anyway.
Note (from MPLUGIN-418):
> The failure message should add a hint that the prerequisites element is not inherited (https://maven.apache.org/ref/3.8.6/maven-model-builder/#inheritance-assembly). This is a common case for this error.

So it was missed on plugin module creation in first place.
