### ISSUE TITLE
Class-level caches are not restricted, will leak memory with mvnd

### ISSUE THREAD

**Issue by ajarmoniuk** [mojohaus/versions#892]
Maven daemon ([mvnd](https://github.com/apache/maven-mvnd)) keeps loaded plugin classes in memory. This means that caches that we have will only grow with time with such setup.

This ultimately leads to JVMs running out of allocated memory, pods getting recreated, etc., but this should probably be controlled and restricted.

Todo: Introduce a limit to those caches.

**Comment by slawekjaranowski** [comment]
@ajarmoniuk  By the way we don't need special issue, when we provide PR at the same time.

**Comment by ajarmoniuk** [comment]
Ok. Still, I think this should be dealt with in maven-core too (together with the caching). I'm also creating a PR to get rid of the ComparableVersion duplicate in m-v-p.

**Comment by TobiX** [comment]
@ajarmoniuk Thanks. I was hesitant to introduce a new dependency for a size-restricted cache, so my first implementation was unbound.
