### ISSUE TITLE
versions:lock-snapshots after upgrading from 2.13.0 to 2.14.0

### ISSUE THREAD

**Issue by g-chcht** [mojohaus/versions#899]
Hello guys,

Full name:
`org.codehaus.mojo:versions-maven-plugin:2.14.0:lock-snapshots
`

What steps will reproduce the bug?
`mvn -U --batch-mode org.codehaus.mojo:versions-maven-plugin:2.14.0:lock-snapshots`

What is the expected behavior?

> searches the pom for all -SNAPSHOT versions and replaces them with the current timestamp version of that -SNAPSHOT, e.g. -20090327.172306-4

What do you see instead?
`-SNAPSHOT` not replaced in pom.xml

Additional information
- Works perfectly fine in 2.13.0
- KO in 2.14.0+ (we tried 2.14.2)
- I've not seen any change to the behavior documented here : https://www.mojohaus.org/versions/versions-maven-plugin/lock-snapshots-mojo.html

Regards,

**Comment by ajarmoniuk** [comment]
@g-chcht could you provide a pom.xml which contains a snapshot to lock so that we could try to reproduce the issue?

**Comment by ajarmoniuk** [comment]
Never mind, managed to reproduce it with a bespoke pom. And confirmed. Thanks for the report.

**Comment by g-chcht** [comment]
Hey,
Thanks for the quick actions !
Need anything else then ?

**Comment by ajarmoniuk** [comment]
Nope. Again, thanks for the report.
