### ISSUE TITLE
Could not find a suitable constructor in org.codehaus.mojo.versions.SetMojo exception -  2.14.2

### ISSUE THREAD

**Issue by kwsamarasinghe** [mojohaus/versions#902]
Hi,

Ran into the following exception in version 2.14.2, when building a spring project.

Could not find a suitable constructor in org.codehaus.mojo.versions.SetMojo. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at org.codehaus.mojo.versions.SetMojo.class(Unknown Source)
  while locating org.codehaus.mojo.versions.SetMojo

Any help is appreciated.
Thanks

**Comment by ajarmoniuk** [comment]
Hi! The plugin requires maven 3.2.5 or later to work.

**Comment by ajarmoniuk** [comment]
@slawekjaranowski @slachiewicz please close
