### ISSUE TITLE
Typo in dependencyManagementIncludes while validateGAVList 

### ISSUE THREAD

**Issue by atultiwariatul** [mojohaus/versions#906]
https://github.com/mojohaus/versions/blob/e6212227c07f7aa1747c10a51c55191c857a03f2/versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java#L487

At Line No: 487 first parameter to method validateGAVList must be corrected from dependencyManagementIncludes to dependencyManagementExcludes

**Comment by ajarmoniuk** [comment]
Indeed. PRs are welcome.
