### ISSUE TITLE
Enhancement: show duplicate version properties

### ISSUE THREAD

**Issue by davefranken-ah** [mojohaus/versions#909]
When I run `mvn versions:display-property-updates` including the parent versions, it doesn't show any information about where the property is found.

It would be nice for me to see if I have manually specified any version property which is the same (same name and value) as a property in any of the ancestors (parent, grandparent etc). In that case, I could delete my version property and clean up my pom a little bit.

**Comment by slawekjaranowski** [comment]
Generally it looks like rule for enforcer plugin.
Which can check any override properties.

**Comment by slawekjaranowski** [comment]
Not planned in this plugin.
