### ISSUE TITLE
update-properties shouldn't lead to build success if encountering an invalid dependency

### ISSUE THREAD

**Issue by maxime-michel** [mojohaus/versions#939]
Hello, we are happy users of this plugin except for one corner case we sometimes run into and would like feedback about. Imagine the following project:

    <?xml version="1.0" encoding="utf-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
      <modelVersion>4.0.0</modelVersion>

      <groupId>test-group</groupId>
      <artifactId>test-artifact</artifactId>
      <version>DEVELOP-SNAPSHOT</version>

      <properties>
        <magnolia.version>6.2</magnolia.version>
      </properties>

      <dependencies>
        <dependency>
          <groupId>info.magnolia</groupId>
          <artifactId>magnolia-core</artifactId>
          <version>${magnolia.version}</version>
        </dependency>
        
        
        
        
        
      </dependencies>
    </project>

Running `mvn versions:update-properties -DincludeProperties=magnolia.version` will properly update `magnolia.version` to `6.2.30`. However, we a have a job that runs this command overnight. And what happens when the project also includes a dependency that doesn't exist (such as the 2nd one, when uncommented) is that the plugin:

1. will not update the version property (which is what we expect),
2. but Maven will end successfully as if no problem had been encountered!

Would it be possible to include an optional argument to actually make the plugin fail the build in such cases?

**Comment by ajarmoniuk** [comment]
I think this should be possible, but it would probably have to be applied across the board, or where applicable -- which makes it a bit larger.

Perhaps it would be a better idea to request a new rule in the enforcer plugin, since that plugin seems more suitable for this?

**Comment by maxime-michel** [comment]
Thanks for the feedback, we can definitely look into this instead.
