### ISSUE TITLE
Plugin validation issues were detected (warning)

### ISSUE THREAD

**Issue by eitan-rosenberg** [mojohaus/versions#954]
Hello there,

I just replaced apache-maven-3.9.1 with apache-maven-3.9.2.

When I run "versions:use-next-releases" I am getting a warning regarding org.codehaus.mojo:versions-maven-plugin:2.15.0

Can you please shed some light on this warning 

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< Apache.Pool.Tests:Apache.Pool.Tests >-----------------
[INFO] Building Apache.Pool.Tests 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions:2.15.0:use-next-releases (default-cli) @ Apache.Pool.Tests ---
[INFO] Updated org.apache.commons:commons-pool2:jar:2.11.0 to version 2.11.1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.830 s
[INFO] Finished at: 2023-05-11T15:33:13+03:00
[INFO] ------------------------------------------------------------------------
[WARNING] 
[WARNING] Plugin validation issues were detected in 2 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-site-plugin:3.12.1
[WARNING]  * org.codehaus.mojo:versions-maven-plugin:2.15.0
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 

There is a mention of "Plugin validation" in the Release Notes page ( https://maven.apache.org/docs/3.9.2/release-notes.html#notable-new-features )

Thanks in advance for any response.

**Comment by eitan-rosenberg** [comment]
Update: when I use VERBOSE I get :

![image](https://github.com/mojohaus/versions/assets/48506054/4b0f475f-a284-45ce-b799-6305591daf7e)

**Comment by eitan-rosenberg** [comment]
> Looks overly pedantic to me, but I've created a PR to get rid of that.

Well... for my defense all I can say is that I thought that there is a problem ;-)
At my age, EOL is not very far.

**Comment by ajarmoniuk** [comment]
Oh I wasn't saying *you* were being pedantic. :)
