### ISSUE TITLE
Question about "versions:dependency-updates-report"

### ISSUE THREAD

**Issue by eitan-rosenberg** [mojohaus/versions#967]
I am trying to use "versions:dependency-updates-report"

My parameters :
onlyProjectDependencies = true   
maven.version.rules = file:///K:/JavaProjects/MyMaven/MyMaven/maven.version.rules.xml   
onlyUpgradable = true   
dependencyUpdatesReportFormats = xml,html   
verbose = true  

Is there a way to get a report **without it downloading all the dependencies**.(like "versions:display-dependency-updates" do).

Thanks for any response.

**Comment by ajarmoniuk** [comment]
Hi. Not really. Not possible right now. I'm not sure whether it's something that Resolver (which is the backend we're using) can do.

**Comment by eitan-rosenberg** [comment]
> Hi. Not really. Not possible right now.

Thanks.

I will be cheeky now and ask how complex is it to add XML format to "versions:display-dependency-updates"....

**Comment by eitan-rosenberg** [comment]
.
