### ISSUE TITLE
Support multiple values for multiple properties in 'set-property' 

### ISSUE THREAD

**Issue by indrakumaryadav** [mojohaus/versions#971]
My pom structure looks like - and i am using org.codehaus.mojo:versions-maven-plugin:2.16.0
```

 <dependency>
      <groupId>com.foo.bar</groupId>
      <artifactId>manchu-core</artifactId>
      <version>[${myartifact.version}]</version>
    </dependency>
    ...
    <dependency>
      <groupId>com.foo.bar</groupId>
      <artifactId>manchu-extra</artifactId>
      <version>[${mysecondArtifact.version}]</version>
    </dependency>
```
Now i want to set different versions for the property of both versions during Maven build. i tried
 `mvn versions:set-property -Dpropery=myartifact.version -DnewVersion=10.1.1`
but set-propery only set single property and does not set both property values

if I pass it using comma-separated value, it only takes the last property not both

`mvn versions:set-property -Dpropery=myartifact.version -DnewVersion=10.1.1, -Dpropery=mysecondartifact.version -DnewVersion=10.5.1`

**Comment by ajarmoniuk** [comment]
You're passing multiple -Dpropery JVM properties. The property you're supposed to be passing is proper**t**y. Please use the `-X` switch to check the actual properties that you've passed:

```
mvn -X versions:set-property -Dpropery=myartifact.version -DnewVersion=10.1.1, -Dpropery=mysecondartifact.version -DnewVersion=10.5.1
```

The plugin will set all the listed properties to the same version, so what you're trying to do here is not supported.

**Comment by indrakumaryadav** [comment]
Sorry, for the type, that was typing mistake, i am using the correct syntax hence it is working for a single property with a single value,
it is not supported with set-property, so is there any other goal that supports multiple property updates with multiple values?

**Comment by ajarmoniuk** [comment]
No, there isn't one.

**Comment by slawekjaranowski** [comment]
@indrakumaryadav - there is `propertiesVersionsFile`
https://www.mojohaus.org/versions/versions-maven-plugin/set-property-mojo.html#propertiesVersionsFile

Can you use it?
