### ISSUE TITLE
use-releases does not update parent

### ISSUE THREAD

**Issue by alerosmile** [mojohaus/versions#978]
The use-release goal does not update the parent version. The [useReleases](https://github.com/mojohaus/versions/blob/0b860eb781f139eb126a4952d51e87e9bc31f63b/versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java#L118) method does detect required changes, but the 
[updateDependencyVersion](https://github.com/mojohaus/versions/blob/0b860eb781f139eb126a4952d51e87e9bc31f63b/versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java#L503) method fails to write the updated version because [this comparison](https://github.com/mojohaus/versions/blob/0b860eb781f139eb126a4952d51e87e9bc31f63b/versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java#L520) is not valid for `-SNAPSHOT` versions. `Artifact.getVersion()` returns the timestamped version. In this case the version should be compared against `Artifact.getBaseVersion()`.

I don't know why this comparison is needed anyway. Either remove the comparison or compare against `Artifact.getVersion()` and `Artifact.getBaseVersion()` and succeed if one of those succeeds.

**Comment by slawekjaranowski** [comment]
There is IT for `use-latest-versions` 
https://github.com/mojohaus/versions/tree/master/versions-maven-plugin/src/it/it-use-latest-versions-011

So we can create similar for `use-release`

PR with fix are welcome.

**Comment by ajarmoniuk** [comment]
Hi, so it turns out that UseReleasesMojoTest::testProcessParent did not work as intended. Looking into this, but you're also free to provide a fix.
