### ISSUE TITLE
Handle failFast configuration on maven enforcer

### ISSUE THREAD

**Issue by julio-matarranz** [mojohaus/versions#984]
Dear,
Maven enforcer allows to run a rules on all submodules and failling at the end with `failFast` set to `false`.
Could you handle that parameter in your code so your rules could fail only at the end ?
Thank you in advance.
Have a nice day ;)

**Comment by slawekjaranowski** [comment]
`failFast` options of enforcer plugin allow only control if all rules from one enforcer executions will be executed nevermind of status each separate rule.

It not controls on modules level.

https://maven.apache.org/enforcer/maven-enforcer-plugin/enforce-mojo.html#failFast

Can you give an example? Which show what you expect.

**Comment by julio-matarranz** [comment]
Sorry my memory misslead me. 
I mixed it with `-fae` which is only working for tests.
